#!/usr/bin/env python3
"""
KSA Bug Bounty Report Generator

Converts raw bug-hunting notes into high-quality bug bounty reports
following HackerOne/Intigriti/Bugcrowd best practices.

Usage:
    python report_generator.py <notes.txt>
    python report_generator.py <notes.txt> --output report.md

Input format (notes.txt exported from KSA Framework):
    Line 1: Title
    Line 2: Vulnerability Type
    Line 3: Target Domain
    Line 4: Severity
    ---DESCRIPTION---
    Description text...
    ---STEPS---
    Steps to reproduce...
    ---IMPACT---
    Impact description...
    ---REMEDIATION--- (optional)
    Remediation suggestion...
    ---EVIDENCE--- (optional)
    Evidence/notes...
"""

import sys
import argparse
from textwrap import dedent
from datetime import datetime

# Report template
TEMPLATE = """
# {title}

## Summary

| Field | Value |
|-------|-------|
| **Severity** | {severity} |
| **Type** | {vuln_type} |
| **Target** | {target} |
| **Date** | {date} |

## Description

{description}

## Steps to Reproduce

{steps}

## Proof of Concept

{poc}

## Impact

{impact}

## Suggested Fix

{fix}

---
*Generated by KSA Bug Bounty Framework*
""".strip()


def parse_notes(content: str) -> dict:
    """Parse the notes.txt format into structured data."""
    lines = content.strip().split('\n')

    data = {
        'title': '',
        'vuln_type': '',
        'target': '',
        'severity': '',
        'description': '',
        'steps': '',
        'impact': '',
        'remediation': '',
        'evidence': '',
    }

    if len(lines) < 4:
        return data

    # Parse header lines
    data['title'] = lines[0] if len(lines) > 0 else 'Untitled'
    data['vuln_type'] = lines[1] if len(lines) > 1 else 'Unknown'
    data['target'] = lines[2] if len(lines) > 2 else 'N/A'
    data['severity'] = lines[3] if len(lines) > 3 else 'Medium'

    # Parse sections
    current_section = None
    section_content = []

    for line in lines[4:]:
        if line.startswith('---') and line.endswith('---'):
            # Save previous section
            if current_section:
                data[current_section] = '\n'.join(section_content).strip()
            # Start new section
            section_name = line.strip('-').lower()
            current_section = section_name
            section_content = []
        elif current_section:
            section_content.append(line)

    # Save last section
    if current_section:
        data[current_section] = '\n'.join(section_content).strip()

    return data


def generate_title(data: dict) -> str:
    """Generate or enhance the report title."""
    if data['title'] and data['title'] != 'Untitled':
        return data['title']

    vuln_type = data['vuln_type'].lower()

    if 'idor' in vuln_type:
        return "IDOR allows unauthorized access to other users' data"
    elif 'xss' in vuln_type:
        return "Stored XSS allows execution of arbitrary JavaScript"
    elif 'sqli' in vuln_type or 'sql' in vuln_type:
        return "SQL Injection allows database access"
    elif 'auth' in vuln_type:
        return "Authentication bypass allows unauthorized access"
    elif 'ssrf' in vuln_type:
        return "SSRF allows internal network access"
    elif 'rce' in vuln_type:
        return "Remote Code Execution vulnerability"
    else:
        return f"{data['vuln_type']} vulnerability in {data['target']}"


def generate_description(data: dict) -> str:
    """Generate or enhance the description."""
    if data['description']:
        return data['description']

    vuln_type = data['vuln_type'].lower()

    if 'idor' in vuln_type:
        return (
            "An authorization vulnerability was identified where a user can perform "
            "actions on resources they do not own. This occurs due to missing or "
            "insufficient access control checks on the backend."
        )
    elif 'xss' in vuln_type:
        return (
            "A cross-site scripting vulnerability was identified that allows an attacker "
            "to inject malicious JavaScript code that executes in the context of other users' sessions."
        )
    else:
        return (
            f"A {data['vuln_type']} vulnerability was identified that could allow "
            "an attacker to compromise the security of the application."
        )


def generate_steps(data: dict) -> str:
    """Generate or format steps to reproduce."""
    if data['steps']:
        # Ensure steps are numbered
        lines = data['steps'].split('\n')
        formatted = []
        for i, line in enumerate(lines, 1):
            line = line.strip()
            if line:
                if not line[0].isdigit():
                    formatted.append(f"{i}. {line}")
                else:
                    formatted.append(line)
        return '\n'.join(formatted)

    return dedent("""
        1. Log in as a low-privileged user
        2. Navigate to the affected endpoint
        3. Intercept the request using a proxy (Burp Suite / similar)
        4. Modify the relevant parameter
        5. Forward the request to the server
        6. Observe the unauthorized action/data access
    """).strip()


def generate_poc(data: dict) -> str:
    """Generate proof of concept section."""
    if data.get('evidence'):
        return data['evidence']

    return dedent("""
        **Example Request:**

        ```http
        GET /api/v1/resource/12345 HTTP/1.1
        Host: {target}
        Authorization: Bearer REDACTED_TOKEN
        ```

        **Example Response:**

        ```json
        HTTP/1.1 200 OK
        {{
            "user_id": "12345",
            "email": "victim@example.com"
        }}
        ```
    """.format(target=data.get('target', 'target.com'))).strip()


def generate_impact(data: dict) -> str:
    """Generate or enhance impact description."""
    if data['impact']:
        return data['impact']

    vuln_type = data['vuln_type'].lower()

    if 'idor' in vuln_type:
        return (
            "An attacker can enumerate resource identifiers to access sensitive data "
            "belonging to other users. This could lead to exposure of personal data, "
            "account takeover vectors, or regulatory compliance issues depending on "
            "the affected endpoint."
        )
    elif 'xss' in vuln_type:
        return (
            "An attacker can execute arbitrary JavaScript in victims' browsers, potentially "
            "leading to session hijacking, credential theft, or actions on behalf of the user."
        )
    elif 'sqli' in vuln_type:
        return (
            "An attacker can extract, modify, or delete data from the database, potentially "
            "gaining access to sensitive information or escalating privileges."
        )
    else:
        return (
            "An attacker could exploit this vulnerability to compromise user data, "
            "perform unauthorized actions, or gain further access to the system."
        )


def generate_fix(data: dict) -> str:
    """Generate remediation suggestion."""
    if data['remediation']:
        return data['remediation']

    vuln_type = data['vuln_type'].lower()

    if 'idor' in vuln_type:
        return (
            "Ensure that the backend validates ownership of the requested resource "
            "for the authenticated user. Implement proper authorization checks and "
            "avoid relying on client-supplied identifiers."
        )
    elif 'xss' in vuln_type:
        return (
            "Implement proper output encoding for all user-controlled data. Use "
            "Content-Security-Policy headers and avoid using innerHTML or similar "
            "dangerous functions with untrusted data."
        )
    elif 'sqli' in vuln_type:
        return (
            "Use parameterized queries or prepared statements instead of string "
            "concatenation. Implement input validation and apply the principle of "
            "least privilege for database accounts."
        )
    else:
        return (
            "Review the affected functionality and implement appropriate security "
            "controls such as input validation, output encoding, and proper "
            "authorization checks."
        )


def generate_report(data: dict) -> str:
    """Generate the full report from parsed data."""
    return TEMPLATE.format(
        title=generate_title(data),
        severity=data['severity'] or 'Medium',
        vuln_type=data['vuln_type'] or 'Security Issue',
        target=data['target'] or 'N/A',
        date=datetime.now().strftime('%Y-%m-%d'),
        description=generate_description(data),
        steps=generate_steps(data),
        poc=generate_poc(data),
        impact=generate_impact(data),
        fix=generate_fix(data),
    )


def main():
    parser = argparse.ArgumentParser(
        description='Generate bug bounty reports from notes'
    )
    parser.add_argument('notes_file', help='Path to notes.txt file')
    parser.add_argument(
        '-o', '--output',
        help='Output file path (default: stdout)'
    )

    args = parser.parse_args()

    try:
        with open(args.notes_file, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: File not found: {args.notes_file}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        sys.exit(1)

    data = parse_notes(content)
    report = generate_report(data)

    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(report)
        print(f"Report saved to: {args.output}")
    else:
        print("\n" + "=" * 60)
        print(report)
        print("=" * 60 + "\n")


if __name__ == "__main__":
    main()
